### ISSUE TITLE
Snapchat cert pinning works partially

### ISSUE THREAD

**Issue by UberFluff** [liamcottle/SnapchatCertPinning#3]
Hello, I tried to sniff snapchat traffic with charles proxy, I installed the cert on my phone connected to the proxy, everything works fine except for apps with cert pinning. So I install your app and now only some of snapchat's request success it's /bq/update_events_v2 that only works, all the other fail.
Can you tell me if it's a problem with the app or my setup ?

I'm on asus zenfone 2 android 5.0 and charles proxy is on my windows 10 computer

**Comment by treestompz** [comment]
@UberFluff you were actually able to login? I seem to be getting blocked by https://www.googleapis.com/androidantiabuse/

**Comment by UberFluff** [comment]
Well I was already logged in since you can't log in while there's xposed so I just installed xposed, then SnapchatCertPinning and now I'm stuck :/

**Comment by KyleBoyer** [comment]
@UberFluff Uninstall xposed framework and installer apk/magisk, then reboot and log into snapchat, then reinstall the xposed framework, and installer and reenable/reinstall this repo and try again.

**Comment by UberFluff** [comment]
@KyleBoyer hey thanks for the answer ! Sadly I'm not into Snapchat sniffing anymore, the token generation is a bit too hard for me and I don't have the time to learn about how it works
Have a great day
